- name: Playbook
  hosts: area4machines
  become: yes
  become_user: root
  tasks:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - curl
        - ca-certificates
        - gnupg
        - lsb-release
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin